export const MAX_CSV_FILE_SIZE_BYTES = 2 * 1024 * 1024;

export const IMPORT_ERROR_CODES = {
  USERNAME_REQUIRED: 'USERNAME_REQUIRED',
  USERNAME_INVALID: 'USERNAME_INVALID',
  EMAIL_INVALID: 'EMAIL_INVALID',
  EMAIL_DUPLICATE_IN_FILE: 'EMAIL_DUPLICATE_IN_FILE',
  EMAIL_DUPLICATE_IN_DB: 'EMAIL_DUPLICATE_IN_DB',
} as const;

export type ImportErrorCode =
  (typeof IMPORT_ERROR_CODES)[keyof typeof IMPORT_ERROR_CODES];
